# Simple Docker Compose for LumiLink Backend

services:
  # Development service
  backend-dev:
    image: node:20-alpine
    working_dir: /app
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - PORT=3001
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    command: sh -c "npm install && npm start"
    restart: unless-stopped
